name: "PR: JSON Changes"

on:
  pull_request:
      branches: [main]
      paths:
       - '**.json'

jobs:
  Validate:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        
      - name: Validate JSON Syntax
        uses: limitusus/json-syntax-check@94555527ace7b96df4a600874a4aafd735842780 # v2
        with:
          pattern: "\\.json$"
