name: "PR: Linter"

on:
  pull_request:
    branches: [main]
    types: [ready_for_review, opened, synchronize, reopened]

jobs:
  Validate:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2

      - name: Lint Codebase
        uses: github/super-linter@bb2d833b08b6c288608686672b93a8a4589cdc49 # v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_YAML: false
          VALIDATE_GITLEAKS: false
          VALIDATE_MARKDOWN: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
