# This workflow outlines tasks that are ran when a new tag is made, typically releasing a new plugin version.

name: "Tag: Release"

on:
  push:
    tags:
      - 'v*.*.*.*'
  


permissions:
  contents: write

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Download Dalamud Library
        run: |
          cd XIVITAGuide
          wget -O Dalamud.zip https://goatcorp.github.io/dalamud-distrib/latest.zip
          unzip -o -d Dalamud Dalamud.zip
          export IsCI=true

      - name: Get Tag Name
        id: tag_name
        shell: bash
        run: >-
          echo "::set-output name=TAG::$(echo ${{ github.ref }} | sed 's/refs\/tags\///' | sed 's/v//')"

      - name: Build Plugin
        shell: bash
        run: |
          dotnet build --configuration Release --nologo -p:AssemblyVersion=${{ steps.tag_name.outputs.TAG }} -p:AssemblyInformationalVersion=${{ steps.tag_name }}
          sha512sum XIVITAGuide/bin/x64/Release/XIVITAGuide/latest.zip  >> checksums.txt
          sha512sum XIVITAGuide/bin/x64/Release/XIVITAGuide/XIVITAGuide.json >> checksums.txt
          cat checksums.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: false
          files: |
            XIVITAGuide/bin/x64/Release/XIVITAGuide/latest.zip
            XIVITAGuide/bin/x64/Release/XIVITAGuide/XIVITAGuide.json
            checksums.txt
