# This workflow outlines tasks that are ran when a new tag is made, typically releasing a new plugin version.

name: "Tag: Release"

on:
  push:
    tags:
      - "v*.*.*.*"

permissions:
  contents: write

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@608ee757cfcce72c2e91e99aca128e0cae67de87 # v1
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Download Dalamud Library
        run: |
          cd XIVITASanctuary
          wget -O Dalamud.zip https://goatcorp.github.io/dalamud-distrib/latest.zip
          unzip -o -d Dalamud Dalamud.zip
          export IsCI=true

      - name: Get Tag Name
        id: tag_name
        shell: bash
        run: >-
          echo "::set-output name=TAG::$(echo ${{ github.ref }} | sed 's/refs\/tags\///' | sed 's/v//')"

      - name: Build Plugin
        shell: bash
        run: |
          dotnet build --configuration Release --nologo -p:AssemblyVersion=${{ steps.tag_name.outputs.TAG }} -p:AssemblyInformationalVersion=${{ steps.tag_name }}
          sha512sum XIVITASanctuary/bin/x64/Release/XIVITASanctuary/latest.zip  >> checksums.txt
          sha512sum XIVITASanctuary/bin/x64/Release/XIVITASanctuary/XIVITASanctuary.json >> checksums.txt
          cat checksums.txt

      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          generate_release_notes: true
          prerelease: false
          files: |
            XIVITASanctuary/bin/x64/Release/XIVITASanctuary/latest.zip
            XIVITASanctuary/bin/x64/Release/XIVITASanctuary/XIVITASanctuary.json
            checksums.txt